
# creating dataframe

In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\pc\appdata\roaming\python\python313\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pc\appdata\roaming\python\python313\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pc\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\pc\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Python313\python.exe -m pip install --upgrade pip

In [2]:
pip uninstall numpy pandas -y
pip install numpy pandas --upgrade
pip install numpy==1.24.4 pandas==1.5.3
conda uninstall numpy pandas -y
conda install numpy pandas

SyntaxError: invalid syntax (3441187514.py, line 1)

In [3]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\pc\appdata\roaming\python\python313\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pc\appdata\roaming\python\python313\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pc\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\pc\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Python313\python.exe -m pip install --upgrade pip

In [4]:
#creating Dataframe
import pandas as pd

In [5]:
data={'name':['jogesh','prateek','dhruv','digvijay'],'Age':[25,30,35,40],'city':['agra','merut','noida','sonipat']}

In [6]:
print(data)

{'name': ['jogesh', 'prateek', 'dhruv', 'digvijay'], 'Age': [25, 30, 35, 40], 'city': ['agra', 'merut', 'noida', 'sonipat']}

In [7]:
type(data)

dict

In [8]:
df=pd.DataFrame(data)

In [9]:
df

       name  Age     city
0    jogesh   25     agra
1   prateek   30    merut
2     dhruv   35    noida
3  digvijay   40  sonipat

In [10]:
df[1:3]

      name  Age   city
1  prateek   30  merut
2    dhruv   35  noida

In [11]:
df.head(2)

       name  Age     city
0    jogesh   25     agra
1   prateek   30    merut
2     dhruv   35    noida
3  digvijay   40  sonipat

In [12]:
df.head(3)

      name  Age   city
0   jogesh   25   agra
1  prateek   30  merut
2    dhruv   35  noida

In [13]:
df.tail(1)

       name  Age     city
3  digvijay   40  sonipat

In [14]:
df.tail(2)

       name  Age     city
2     dhruv   35    noida
3  digvijay   40  sonipat

In [15]:
# it shows rows and columns
df.shape

(4, 3)

In [16]:
df.name

0      jogesh
1     prateek
2       dhruv
3    digvijay
Name: name, dtype: object

In [17]:
df2=df['name']

In [18]:
df2

0      jogesh
1     prateek
2       dhruv
3    digvijay
Name: name, dtype: object

In [19]:
dddfff=df.name

In [20]:
dddfff

0      jogesh
1     prateek
2       dhruv
3    digvijay
Name: name, dtype: object

In [21]:
df3=df['name'and 'Age']

In [22]:
df3

0    25
1    30
2    35
3    40
Name: Age, dtype: int64

In [23]:
df3,df2

(0    25
 1    30
 2    35
 3    40
 Name: Age, dtype: int64,
 0      jogesh
 1     prateek
 2       dhruv
 3    digvijay
 Name: name, dtype: object)

In [24]:
#ek sth age or name dono sth lene ki baat khi thi
df4=df[['name','Age']]

In [25]:
df4

       name  Age
0    jogesh   25
1   prateek   30
2     dhruv   35
3  digvijay   40

In [26]:
df5=df[['name','Age','city']]

In [27]:
df5

       name  Age     city
0    jogesh   25     agra
1   prateek   30    merut
2     dhruv   35    noida
3  digvijay   40  sonipat

In [28]:
df5.loc[0]

name    jogesh
Age         25
city      agra
Name: 0, dtype: object

In [29]:
df5.loc[0:2]

      name  Age   city
0   jogesh   25   agra
1  prateek   30  merut
2    dhruv   35  noida

In [30]:
df5.iloc[0:2]

      name  Age   city
0   jogesh   25   agra
1  prateek   30  merut

In [31]:
df5.iloc[0]

name    jogesh
Age         25
city      agra
Name: 0, dtype: object

In [32]:
df5.loc[0]

name    jogesh
Age         25
city      agra
Name: 0, dtype: object

In [33]:
df["gender"]=['M','M','M','M']

In [34]:
df

       name  Age     city gender
0    jogesh   25     agra      M
1   prateek   30    merut      M
2     dhruv   35    noida      M
3  digvijay   40  sonipat      M

In [35]:
del df["gender"]

In [36]:
df

       name  Age     city
0    jogesh   25     agra
1   prateek   30    merut
2     dhruv   35    noida
3  digvijay   40  sonipat

In [37]:
filter_age=df['Age']<35

In [38]:
filter_age

0     True
1     True
2    False
3    False
Name: Age, dtype: bool

In [39]:
filter_age=df[df['Age']<35]

In [40]:

filter_age

      name  Age   city
0   jogesh   25   agra
1  prateek   30  merut

In [41]:
sorted_df=df.sort_values('Age')

In [42]:
sorted_df

       name  Age     city
0    jogesh   25     agra
1   prateek   30    merut
2     dhruv   35    noida
3  digvijay   40  sonipat

In [43]:
df.sort_values(by='Age', ascending=False )

       name  Age     city
3  digvijay   40  sonipat
2     dhruv   35    noida
1   prateek   30    merut
0    jogesh   25     agra

In [44]:
#merge data
ds={'name':['jogesh','prateek','dhruv','digvijay'],'salary':[5000,6000,7000,20]}

In [45]:
ds1=pd.DataFrame(ds)

In [46]:
ds1

       name  salary
0    jogesh    5000
1   prateek    6000
2     dhruv    7000
3  digvijay      20

In [47]:
merge_data=ds1.merge(df5,on='name')

In [48]:
merge_data

       name  salary  Age     city
0    jogesh    5000   25     agra
1   prateek    6000   30    merut
2     dhruv    7000   35    noida
3  digvijay      20   40  sonipat

In [49]:
ds1.info

<bound method DataFrame.info of        name  salary
0    jogesh    5000
1   prateek    6000
2     dhruv    7000
3  digvijay      20>

In [50]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   Age     4 non-null      int64
 2   city    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [56]:
df5['age']=df['Age'].astype(str)

In [57]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   Age     4 non-null      int64
 2   city    4 non-null      object
 3   age     4 non-null      object
dtypes: int64(1), object(3)
memory usage: 260.0+ bytes

In [58]:
df

       name  Age     city
0    jogesh   25     agra
1   prateek   30    merut
2     dhruv   35    noida
3  digvijay   40  sonipat

In [59]:
# inplace=True lete h to dono variables change hoga
#inplace=False lete h ya normal likh de bina inplace ke to original data bch jaega

In [62]:
df.rename(columns={'name':'Full name'},inplace=True)
df

In [63]:
df

  Full name  Age     city
0    jogesh   25     agra
1   prateek   30    merut
2     dhruv   35    noida
3  digvijay   40  sonipat

In [52]:
df

       name  Age     city
0    jogesh   25     agra
1   prateek   30    merut
2     dhruv   35    noida
3  digvijay   40  sonipat

In [53]:
#duplicates value ko remove krke unique values rkhega

In [54]:
df2.drop_duplicates()

0      jogesh
1     prateek
2       dhruv
3    digvijay
Name: name, dtype: object

In [55]:
df.describe()

             Age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

# Numpy library

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5])

In [ ]:
arr1 # one dimensional array h

In [ ]:
arr1*2

In [ ]:
lis=[2,3,4,5,6]
for i in lis:
    print(2*i,end=' ') #end is use to terminate the line by line and fr compiler smjhta h ki 1 hi line me print dega

In [ ]:
#isme sirf int specify kr skte h islie +2 kr rha h

In [ ]:
arr1+2

In [ ]:
lis*2 #isme ye 2 baar likh dega

In [ ]:
# two dimensional array krenge iska mtlb row and column base pe iska mtlb ab matrix lega

In [ ]:
arr2=np.array([[13,42,42,5,8,10],[4,5,8,8,10,1]])

In [ ]:
arr2

In [ ]:
arr2.dtype

In [ ]:
arr2.shape # iska mtlb 2 row and 6 column

In [ ]:
arr=np.arange(0,10,2) # iska mtlb ye matrix ka starting point and ending point with interval

In [ ]:
arr

In [ ]:
array1=np.array([2,4,6,8,14])

In [ ]:
array2=np.array([6,12,8,10,12])

In [ ]:
array1*2

In [ ]:
array1*array2

In [ ]:
array1/array2

In [ ]:
array1[::-1] # slicing h ye isme

In [ ]:
np.sum(array1)

# Sum and Multiply of elements in a list by using For loop

In [ ]:
li=[4,5,6,6,5,7]
sum=0
for i in li:
    sum=sum+i
print(sum)

In [ ]:
li=[4,5,6,6,5,7]
nu=1
for i in li:
    nu=nu*i
print(nu)

In [ ]:
array1

In [ ]:
np.max(array1)

In [ ]:
np.min(array1)

In [ ]:
#calculate statistical array
#array=array_number=[2,4,6,7,18,14]

In [ ]:
array=array_number=[2,4,6,7,18,14]

In [ ]:
ar=np.array([10,12,15,13,14,47,98,52,15,34,45,65,23,45,65])

In [ ]:
np.median(array)

In [ ]:
np.mean(ar)

In [ ]:
np.std(ar)

In [ ]:
np.median(ar)

In [ ]:
np.mean(array)

In [ ]:
np.std(array)

# sum of list to list

In [ ]:
list1=[2,3,5,6]
list2=[5,8,5,9]
list3=[]

In [ ]:
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])
print(list3)

In [ ]:
list3

# Multiply list to list

In [ ]:
list4=[]

In [ ]:
for i in range(len(list1)):
    list4.append(list1[i]*list2[i])
print(list3)

In [ ]:
list4

In [ ]:
list2

# To Find maxi and mini from the list without using max and mini pre-defined function.

In [ ]:
list2.sort()

In [ ]:
print(list2[-1])

In [ ]:
lst=[5,4,80,14,65,74]

In [ ]:
lst.sort()

In [ ]:
print(lst[-1])

In [ ]:
print(lst[0])